# Generated by Django 3.2.4 on 2021-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='member', max_length=20)),
                ('flat_address', models.CharField(default='abc', max_length=20)),
                ('car_number', models.CharField(default='abc12', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='abc', max_length=20)),
                ('car_number', models.CharField(default='abc12', max_length=15)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('entry_timing', models.TimeField()),
                ('exit_timing', models.TimeField()),
                ('exit_allow', models.BooleanField(default=True)),
            ],
        ),
    ]
