# Generated by Django 3.2.4 on 2021-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='flat_address',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
