# Generated by Django 3.2.4 on 2021-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20210621_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='member',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
