# Generated by Django 3.2.4 on 2021-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_vehicles_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='four_wheeler',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
