# Generated by Django 3.2.4 on 2021-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_vehicles_four_wheeler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='exit_allow',
        ),
        migrations.AddField(
            model_name='members',
            name='exit_allow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='members',
            name='four_wheeler',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
