# Generated by Django 3.2.4 on 2021-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_auto_20210622_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='purpose',
            field=models.TextField(blank=True, default='-----'),
        ),
    ]
