# Generated by Django 3.2.4 on 2021-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_vehicles_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='entry_timing',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='exit_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='exit_timing',
            field=models.TimeField(blank=True),
        ),
    ]
